# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0ff5172426c9fdafaf58d9165795e0584dbd32d16dc4f7128fd4efa7168202e3a9390488595cfbbc87a937f099ac5c6535faa19443bd223121933f7c03be908

test:
  secret_key_base: 0203df2ad82bad73979183be6dfaa8fa72ff24980ab3ad947ebd77f705747e4f659e18e069d7bdf67d9f84a6afb302fd1ea869d9eb8fdaf032c18c61b0861db3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
